development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: the_social_sphere

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: the_social_sphere_production
